### ISSUE TITLE
Add sorting algorithm in c language

### ISSUE THREAD

**Issue by navdiya-nikunj** [navdiya-nikunj/DSA-beginner-friendly#11]
## Add sorting algorithm in c language
 `it should be in algorithms/c-language/sorting`

**Comment by aishwarya1735** [comment]
Can this issue be assigned to me?

**Comment by tausifaman222** [comment]
Kindly, Assign this issue to me .

**Comment by roshan71** [comment]
I already add all sorting algorithm and made pull request.
So please assign this problem to me and mark my solution!!!

**Comment by navdiya-nikunj** [comment]
Sure i will look your pr

**Comment by navdiya-nikunj** [comment]
For other guys there are so many new issues you can contribute in anyone look for it in our repo
