### ISSUE TITLE
Dictionary in Python

### ISSUE THREAD

**Issue by tapaskhanijo** [navdiya-nikunj/DSA-beginner-friendly#16]
Performing different operations on **`dictionary`** Data Structure in Python!

**Comment by navdiya-nikunj** [comment]
Make new folder for it 
Thanks for contributing 🙂

**Comment by tapaskhanijo** [comment]
sure! have added a new folder named ` DATA STRUCTURES in PYTHON` which contains `dictionary`'s basic intro.
of course:)
