### ISSUE TITLE
Binary Search Algorithm in C++.

### ISSUE THREAD

**Issue by kittusinghkumar** [navdiya-nikunj/DSA-beginner-friendly#21]
Binary Search Algorithm in C++

**Comment by kittusinghkumar** [comment]
Pull : https://github.com/navdiya-nikunj/DSA-beginner-friendly/pull/33

**Comment by kittusinghkumar** [comment]
Kindly look into it @navdiya-nikunj

**Comment by navdiya-nikunj** [comment]
Can you please add comments in code for beginners
