### ISSUE TITLE
Selection Sort Algorithm in C++

### ISSUE THREAD

**Issue by kittusinghkumar** [navdiya-nikunj/DSA-beginner-friendly#22]
Selection Sort Algorithm in C++

**Comment by navdiya-nikunj** [comment]
If you want to work on it then tell me.

**Comment by kittusinghkumar** [comment]
Yes

**Comment by kittusinghkumar** [comment]
Pull Request : https://github.com/navdiya-nikunj/DSA-beginner-friendly/pull/36
