### ISSUE TITLE
Selection Sort in Python

### ISSUE THREAD

**Issue by kittusinghkumar** [navdiya-nikunj/DSA-beginner-friendly#28]
add selection sort in python

**Comment by navdiya-nikunj** [comment]
if you want to work on it you can tell me. 
thanks for contributing 🙂.

**Comment by kittusinghkumar** [comment]
Pull Request : https://github.com/navdiya-nikunj/DSA-beginner-friendly/pull/40

**Comment by kittusinghkumar** [comment]
Kindly add the hacktoberfest label @navdiya-nikunj
