### ISSUE TITLE
Make README.md more attractive by adding socalify and contributors

### ISSUE THREAD

**Issue by PeritusDeveloper** [navdiya-nikunj/DSA-beginner-friendly#79]
- Glimpse
<img width="470" alt="image" src="https://user-images.githubusercontent.com/89828000/193835543-fbbf606a-9c2f-459e-9f70-5b49625190aa.png">

- Automatically adding contributors to README file with their profile pictures

**Comment by navdiya-nikunj** [comment]
Can you do that for us?
if yes then mention me i will assign it to you .
Thanks for creating issue.🙂

**Comment by PeritusDeveloper** [comment]
Yes I will do it
please assign it to me

**Comment by PeritusDeveloper** [comment]
Can you add hacktoberfest to your repository
Or will you add hacktoberfest-accepted in PR because I can't see anyone getting this label

**Comment by navdiya-nikunj** [comment]
This repo is excluded so it won't count but still I can add it if you want
